title = "Loopring TOML"

[owner]
name = "Loopring corporation"

[order_book]

[log_dir]
log_path = ["/Users/fukun/projects/gohome/src/github.com/Loopring/ringminer/zap.log", "stderr"]
err_path = ["/Users/fukun/projects/gohome/src/github.com/Loopring/ringminer/err.log"]

[database]
server = "localhost"
port = 8001
data_dir = "./leveldb"
name = "leveldb"
cache_capacity = 8
buffer_capacity = 4

[ipfs]
server = "localhost"
port = 8080
topic = "test1_topic"

[chain_client]
raw_url = "http://127.0.0.1:8545"
passphrase = "sa"
[chain_client.senders]
"0xb5fab0b11776aad5ce60588c16bd59dcfd61a1c2" = "0xfa9a051f7919ec415d9d2a7c729ef4b4762c6ab57efd4b9fcedcb509518b173d"
"0x48ff2269e58a373120FFdBBdEE3FBceA854AC30A" = "0xec1da652e6e40648c6b474e706d7fe09091fb775a38cef706d603c250db5d872"
    [chain_client.eth]
        gas_price = 10000
        gas_limit = 10000

[common]
loopringImpAddresses = ["0x2c9567f1b64F20B8911635bcddF640459Ddf36a9"]
filter_topics = ["order_filled", "order_cancelled", "ring_mined", "cut_off_timestamp_changed"]
default_block_number = 15813
end_block_number = 100000000000000

[miner]
ringMaxLength = 4
feeRecepient = ""
passphrase = "sa"
miner = "0xfa9a051f7919ec415d9d2a7c729ef4b4762c6ab57efd4b9fcedcb509518b173d"
ifRegistryRingHash = false
rate_ratio_cvs_threshold = 1000000000000000

[miner.rate_provider]
lrc_address = "0x5132a8ce9a61b13b9cAEcd2261abF95323056423"
base_url = "https://api.coinmarketcap.com/v1/ticker/%s/?convert=CNY"
currency = "USD"
[miner.rate_provider.currencies_map]
"0x5132a8ce9a61b13b9cAEcd2261abF95323056423" = "Loopring"
