title = "Loopring TOML"

[owner]
name = "Loopring corporation"

[order_book]

[log]
    [log.zap_opts]
    level = "debug"
    development = true
    disable_stacktrace = false
    encoding = "console"
    output_paths = ["zap.log", "stderr"]
    error_output_paths = ["err.log"]
        [log.zap_opts.encoder_config]
	    message_key = "msg"
	    level_key = "level"
	    stacktrace_key = "trace"
	    time_key = "ts11111"
	    encode_level = "lowercase"
	    encode_time = "iso8601"

[database]
    server = "localhost"
    port = 8001
    data_dir = "./leveldb"
    name = "leveldb"
    cache_capacity = 8
    buffer_capacity = 4

[ipfs]
    server = "localhost"
    port = 8080
    topic = "test1_topic"

[chain_client]
raw_url = "http://10.137.109.101:8545"
[chain_client.senders]
    "0xb5fab0b11776aad5ce60588c16bd59dcfd61a1c2" = "0xfa9a051f7919ec415d9d2a7c729ef4b4762c6ab57efd4b9fcedcb509518b173d"
    "0x48ff2269e58a373120FFdBBdEE3FBceA854AC30A" = "0xec1da652e6e40648c6b474e706d7fe09091fb775a38cef706d603c250db5d872"
    [chain_client.eth]
        gas_price = 10000
        gas_limit = 10000

[common]
loopringImpAddresses = ["0xbc887ce07cee5624715f6ff39e1dd6603633c777"]
filter_topics = ["order_filled", "order_cancelled", "ring_mined", "cut_off_timestamp_changed"]
default_block_number = 4195
end_block_number = 4197
develop = true

[miner]
    ringMaxLength = 4
    feeRecepient = ""
    miner = "0xfa9a051f7919ec415d9d2a7c729ef4b4762c6ab57efd4b9fcedcb509518b173d"
    ifRegistryRingHash = false
    rate_ratio_cvs_threshold = 1000000000000000

[miner.rate_provider]
    lrc_address = "0x5132a8ce9a61b13b9cAEcd2261abF95323056423"
    base_url = "https://api.coinmarketcap.com/v1/ticker/%s/?convert=CNY"
    currency = "USD"
        [miner.rate_provider.currencies_map]
        "0x5132a8ce9a61b13b9cAEcd2261abF95323056423" = "Loopring"
