title = "Loopring TOML"

[owner]
name = "Loopring corporation"

[order_book]
filter_topics = ["order_filled", "order_cancelled", "ring_mined", "cut_off_timestamp_changed"]
default_block_number = 100

[database]
server = "localhost"
port = 8001
data_dir = "./leveldb"
name = "leveldb"
cache_capacity = 8
buffer_capacity = 4

[ipfs]
server = "localhost"
port = 8080
topic = "test_topic"

[chain_client]
raw_url = "http://127.0.0.1:8545"
passphrase = "sa"
[chain_client.senders]
"0xA16992135207c57A569AeB2E6455B97Ec35A833d" = "0x6696d1c16b04875a2f3d2fcbab3fd6af16fd27d7a813cb69cb5cbf678b81e0df"
    [chain_client.eth]
        gas_price = 10000
        gas_limit = 10000