title = "Loopring TOML"

[owner]
name = "Loopring corporation"

[order_book]


[database]
server = "localhost"
port = 8001
data_dir = "./leveldb"
name = "leveldb"
cache_capacity = 8
buffer_capacity = 4

[ipfs]
server = "localhost"
port = 8080
topic = "test_topic"

[chain_client]
raw_url = "http://127.0.0.1:8545"
passphrase = "sa"
[chain_client.senders]
"0xb5fab0b11776aad5ce60588c16bd59dcfd61a1c2" = "0xfa9a051f7919ec415d9d2a7c729ef4b4762c6ab57efd4b9fcedcb509518b173d"
"0x48ff2269e58a373120FFdBBdEE3FBceA854AC30A" = "0xec1da652e6e40648c6b474e706d7fe09091fb775a38cef706d603c250db5d872"
    [chain_client.eth]
        gas_price = 10000
        gas_limit = 10000

[common]
loopringImpAddresses = ["0xa221f7c8cd24a7a383d116aa5d7430b48d1e0063"]
filter_topics = ["order_filled", "order_cancelled", "ring_mined", "cut_off_timestamp_changed"]
default_block_number = 100

[miner]
ringMaxLength = 4
feeRecepient = ""
miner = "0xfa9a051f7919ec415d9d2a7c729ef4b4762c6ab57efd4b9fcedcb509518b173d"
ifRegistryRingHash = false
